### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by zhaokun-jpg** [ahmadnassri/action-workflow-queue#36]
output：

```
Run ahmadnassri/action-workflow-queue@v1
/usr/bin/docker run --name ghcrioahmadnassriactionworkflowqueue114_fc3184 --label 2a[6](https://github.com/xxxxx#step:4:7)c8c --workdir /github/workspace --rm -e "INPUT_GITHUB-TOKEN" -e "INPUT_TIMEOUT" -e "INPUT_DELAY" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/axxxx/xxxx":"/github/workspace" ghcr.io/ahmadnassri/action-workflow-queue:1.1.4
Error: Resource not accessible by integration
HttpError: Resource not accessible by integration
    at /action/node_modules/@octokit/request/dist-node/index.js:[8](https://github.com/xxxx#step:4:9)6:21
    at process.processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/xxxxxx#step:4:10)5:5)
    at async default (file:///action/lib/index.js:23:53)
    at async file:///action/index.js:34:1
```

workflow.ymal:

```
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v3

      - name: Workflow Queue check
        uses: ahmadnassri/action-workflow-queue@v1

```

**Comment by zhaokun-jpg** [comment]
Replaced this component with the `concurrency` keyword

**Comment by luka-bacic** [comment]
Hi @zhaokun-jpg could you please post your solution? I'm facing the same issue as you

> Replaced this component with the `concurrency` keyword

**Comment by davidwangqing** [comment]
> Hi @zhaokun-jpg could you please post your solution? I'm facing the same issue as you
> 
> > Replaced this component with the `concurrency` keyword
Git hub action support concurrency check for jobs, [https://docs.github.com/en/actions/using-jobs/using-concurrency](https://docs.github.com/en/actions/using-jobs/using-concurrency)

**Comment by davidwangqing** [comment]
I'm facing the same problem, after some investigation, it turns out that the permission of repository action was misconfigured,  check the action permission configuration following the image below.
![image](https://github.com/ahmadnassri/action-workflow-queue/assets/134319487/8ec90dfe-dd54-455f-9045-c663017e6358)

**Comment by camelaissani** [comment]
Added `read` to the `actions` and `contents` permissions solved the issue on my side:

```
 install:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Queue workflow if already running
      uses: ahmadnassri/action-workflow-queue@v1
```
